#Ataza honek samba eta bere dependentziak instalatzen ditu. Aurretik instalatuta badago, zerbitzua gelditzen du.
---
- name: Install dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - samba
     - krb5-user
     - krb5-config
     - krb5-pkinit
     - winbind
     - smbclient
     - libpam-winbind
     - libnss-winbind

- name: Aurretik konfiguratutako smbd zerbitzua gelditu.
  service:
    name: smbd
    state: stopped

- name: Aurretik konfiguratutako nmbd zerbitzua gelditu.
  service:
    name: nmbd
    state: stopped

- name: Aurretik konfiguratutako winbind zerbitzua gelditu.
  service:
    name: winbind
    state: stopped

- name: Aurretik konfiguratutako samba zerbitzua gelditu.
  service:
    name: samba
    state: stopped

- name: Aurretik konfiguratutako samba-ad-dc zerbitzua gelditu.
  service:
    name: samba-ad-dc
    state: stopped
