#Ataza honek samba zerbitzariaren DNS-ak konfiguratzen ditu
---
- name: Zerbitzariari izena jarri.
  hostname:
    name: DC1

- name: resolv.conf fitxategia aldatu daitekela ziurtatu.
  file:
    path: /etc/resolv.conf
    attr: -i

- name: Aurreko resolv.conf fitxategia ezabatu.
  file:
    path="/etc/resolv.conf"
    state=absent

- name: resolv.conf fitxategi berria sortu.
  blockinfile:
    dest: "/etc/resolv.conf"
    create: "true"
    block: |
     domain {{ full_domain_name }}
     search {{ full_domain_name }}
     nameserver 127.0.0.1

- name: resolv.conf fitxategia automatikoki ez dela aldatuko ziurtatu.
  file:
    path: /etc/resolv.conf
    attr: +i
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"
