#Ataza honetan domeinua konfiguratuko dugu
---
#aurretik samba domeinua konfiguatuta bagenuen dena ezabatu eta berrabiaraziko du
- name: Aurretik konfiguratutako smbd zerbitzua gelditu.
  service:
    name: smbd
    state: stopped

- name: Aurretik konfiguratutako nmbd zerbitzua gelditu.
  service:
    name: nmbd
    state: stopped

- name: Aurretik konfiguratutako winbind zerbitzua gelditu.
  service:
    name: winbind
    state: stopped

- name: Aurretik konfiguratutako samba zerbitzua gelditu.
  service:
    name: samba
    state: stopped

- name: Domeinua aurretik konfiguratuta dagoen ikusi.
  replace:
    path: /etc/samba/smb.conf
    regexp: "realm = {{ full_domain_name | upper }}" #fitxategian maiuskulaz dagoenez 'upper' jartzen dugu
    replace: "hau proba bat da"
  check_mode: yes #aldaketa egin behar den simulatzen du, ez du benetan egiten
  register: smb

- name: Dagoeneko konfiguratuta dago.
  debug: msg="{{ full_domain_name }} konfiguratuta dago."
  when: smb is changed

- name: Aurreko smb.conf fitxategia ezabatu.
  file:
    path="/etc/samba/smb.conf"
    state=absent
  when: smb is not changed

- name: Domeinua konfiguratu. Pasahitza aldatu beharko da.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - provision
      - --server-role=dc
      - --dns-backend=SAMBA_INTERNAL
      - --realm={{ full_domain_name }}
      - --domain={{ domain_name }}
      - --adminpass=DomainPass2
  when: smb is not changed

- name: Sortu berri den kerberos konfigurazioa kopiatu.
  copy:
    src: "/var/lib/samba/private/krb5.conf"
    dest: "/etc/krb5.conf"
    mode: 0600
  when: smb is not changed

- name: Kanpoko DNS zerbitzaria konfiguratu, konexiorik gabe ez gelditzeko.
  replace:
    dest: /etc/samba/smb.conf
    regexp: "dns forwarder = {{ ansible_default_ipv4.address }}"
    replace: "dns forwarder = {{ ansible_default_ipv4.gateway }}"

- name: Samba zerbitzua berrabiarazi.
  service:
    name: samba
    state: restarted
