#Ataza honetan domeinua konfiguratuko dugu eta ldap-bin erabiltzaile funtzionala sortuko dugu
---
- name: Begiratu samba konfiguraziorik dagoen.
  stat:
    path: /etc/samba/smb.conf
  register: smb1

- name: Domeinua aurretik konfiguratuta dagoen ikusi.
  replace:
    path: /etc/samba/smb.conf
    regexp: "realm = {{ full_domain_name | upper }}" #fitxategian maiuskulaz dagoenez 'upper' jartzen dugu
    replace: "hau proba bat da"
  check_mode: yes #aldaketa egin behar den simulatzen du, ez du benetan egiten
  register: smb
  when: smb1.stat.exists == True

- name: Dagoeneko konfiguratuta dago.
  debug: msg="{{ full_domain_name }} konfiguratuta dago."
  when: smb is changed

- name: Aurreko smb.conf fitxategia ezabatu.
  file:
    path="/etc/samba/smb.conf"
    state=absent
  when: smb is not changed

- name: Domeinua konfiguratu. Pasahitza aldatu beharko da.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - provision
      - --server-role=dc
      - --dns-backend=SAMBA_INTERNAL
      - "--realm={{ full_domain_name | upper }}"
      - "--domain={{ domain_name | upper }}"
      - --adminpass=DomainPass2
  when: (smb1.stat.exists == False) or (smb is not changed)

- name: Sortu berri den kerberos konfigurazioa kopiatu.
  copy:
    src: "/var/lib/samba/private/krb5.conf"
    dest: "/etc/krb5.conf"
    mode: 0600
  when: (smb1.stat.exists == False) or (smb is not changed)

- name: ldap erabiltzaile funtzionala sortu. Konektatzeko erabiliko dugu.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - user
      - add
      - ldap-bind
      - --random-password
  when: (smb1.stat.exists == False) or (smb is not changed)

- name: Add spn. ldap erabiltzaileak duen baimena zehaztu.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - spn
      - add
      - "LDAP/{{ full_domain_name }}"
      - ldap-bind
  when: (smb1.stat.exists == False) or (smb is not changed)

- name: Keytab fitxategia sortu.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - exportkeytab
      - /root/ldap.keytab
      - --principal=ldap-bind
  when: (smb1.stat.exists == False) or (smb is not changed)

- name: Kanpoko DNS zerbitzaria konfiguratu, konexiorik gabe ez gelditzeko.
  replace:
    dest: /etc/samba/smb.conf
    regexp: "^(.*)dns forwarder =(.*)$"
    replace: "dns forwarder = {{ ansible_default_ipv4.gateway }}"

- name: Samba zerbitzua berrabiarazi.
  service:
    name: samba
    state: restarted

- name: Samba-ad-dc zerbitzua berrabiarazi.
  service:
    name: samba-ad-dc
    state: restarted
