#Ataza honek samba zerbitzariaren DNS-ak konfiguratzen ditu
---
- name: resolv.conf fitxategia aldatu daitekela ziurtatu.
  file:
    path: /etc/resolv.conf
    attr: -i

- name: Aurreko resolv.conf fitxategia ezabatu.
  file:
    path="/etc/resolv.conf"
    state=absent

- name: resolv.conf fitxategi berria sortu.
  blockinfile:
    dest: "/etc/resolv.conf"
    create: "true"
    block: |
     search {{ full_domain_name }}
     nameserver {{ ansible_default_ipv4.address }}

- name: resolv.conf fitxategia automatikoki ez dela aldatuko ziurtatu.
  file:
    path: /etc/resolv.conf
    attr: +i
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"

- name: Kanpoko DNS zerbitzaria konfiguratu, konexiorik gabe ez gelditzeko.
  replace:
    dest: /etc/samba/smb.conf
    regexp: "dns forwarder = {{ ansible_default_ipv4.address }}"
    replace: "dns forwarder = {{ ansible_default_ipv4.gateway }}"

- name: dns_lookup_realm konfiguratu.
  replace:
    dest: /etc/krb5.conf
    regexp: "dns_lookup_realm = false"
    replace: "dns_lookup_realm = true"
