#Ataza honek domeinuan sartzeko erabiltzailea sortuko du
---
- name: ldap-bind erabiltzailea existitzen den ikusi
  ansible.builtin.shell:
    cmd: samba-tool user list | grep ldap-bind

- name: ldap-bind erabiltzailea existitzen den ikusi
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - user
      - show
      - ldap-bind

- name: ldap erabiltzaile funtzionala sortu.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - user
      - add
      - ldap-bind
      - --random-password

- name: Add spn.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - spn
      - add
      - LDAP/mydomain.org
      - ldap-bind

- name: Export keytab.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - exportkeytab
      - /root/ldap.keytab
      - --principal=ldap-bind
