#Ataza hau zaharra da eta jada ez dugu erabiltzen.
#Pasahitz kudeatzaileak instalatzeko balio du.
---
- name: gnome-keyring eta pam moduloa instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - gnome-keyring
    - libpam-gnome-keyring
    - gnome-keyring-pkcs11

- name: kwallet5 eta pam moduloa instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - kwalletmanager
    - libpam-kwallet5
