#Ataza honek xfce mahaigaina instalatzen du. 
#Ukui ere konfiguratzen du, defektuz xfce abiarazteko.
---
- name: xfce eta adwaita instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xfce4
    - xfce4-terminal
    - gnome-themes-extra
    - mousepad

- name: Automatikokin instalatutako desktop-base eta light-locker paketeak kendu.
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - desktop-base
    - light-locker

- name: Defektuz xfce idazmaia abiarazteko ukui konfiguratu.
  lineinfile:
    dest: /usr/share/lightdm/lightdm.conf.d/95-ukui-greeter.conf
    regexp: "user-session=ukui"
    line: "user-session=xfce"
    backrefs: yes

- name: xfc4-terminal lehenetsi. Ubuntu.
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/xfce4-terminal.wrapper
  when: ansible_distribution == 'Ubuntu'
