#Ataza honek pdfak manipulatzeko ghostscrip instalatuko du.
#Thunarren bi aukera gehituko ditugu pdf-ak batu eta bereizteko.
---
- name: PDF-ak ikusteko programa instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - atril

- name: PDF-ak manipulatzeko programak instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - ghostscript
    - pdftk
    - texlive-extra-utils
    - zenity

- name: PDF-ak bereiztu eta batzeko script-ak kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - pdfakbereiztu
     - pdfakbereiztucli
     - pdfakbatu

- name: Thunar actions aldatu behar den ikusi.
  replace:
    path: /etc/xdg/Thunar/uca.xml
    regexp: "^(.*)pdfakbereiztu(.*)$"
    replace: "hau proba bat da"
  check_mode: yes #aldaketa egin behar den simulatzen du, ez du benetan egiten
  register: uca

- name: Dagoeneko aldatuta dago.
  debug: msg="uca dagoeneko aldatuta dago."
  when: uca is changed

- name: Thunar custom actions. PDF-ak batu eta bereizteko scriptak.
  blockinfile:
    path: /etc/xdg/Thunar/uca.xml
    insertbefore: '</actions>'
    block: |
      <action>
        <icon></icon>
        <patterns>*.pdf;*.PDF</patterns>
        <name>Pdf-ak bereiztu</name>
        <command>/usr/local/bin/pdfakbereiztu %N</command>
        <description></description>
        <other-files/>
      </action>
      <action>
        <icon></icon>
        <patterns>*.pdf;*.PDF</patterns>
        <name>Pdf-ak batu</name>
        <command>/usr/local/bin/pdfakbatu %N</command>
        <description></description>
        <other-files/>
      </action>
  when: uca is not changed
