#Ataza honek arbel digitalarekin erabiltzeko programak instalatzen ditu
---
- name: Xournal instalatu. Bertsio zaharra eta berria.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xournal
    - xournalpp

- name: xournal karpeta sortu skel barruan.
  file:
    path: /etc/skel/.xournal
    state: directory
    mode: 0755

- name: xournal konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/skel/.xournal/config"
    dest: /etc/skel/.xournal/config
    mode: 0644

- name: Pylote programaren dependentziak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - python3-pyqt5
     - python3-pyqt5.qtwebengine
     - python3-pyqt5.qtsvg

- name: Pylote programa deskargatu eta erauzi.
  unarchive:
    src: http://pascal.peter.free.fr/wikiuploads/pylote.tar.gz
    dest: /opt
    remote_src: yes

- name: Pylote programaren lasterbidea kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/pylote.desktop"
    dest: "/usr/share/applications/pylote.desktop"
    mode: 0644
    remote_src: yes
