#Ataza honek chromium nabigatzailea instalatu eta konfiguratzen du.
---
- name: Chromium instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium
    - chromium-l10n

- name: Politiken karpeta sortu.
  file:
    path: /etc/chromium/policies/managed
    state: directory
    mode: 0755

- name: Politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644

- name: master_preferences fitxategia kendu.
  file:
    path: /etc/chromium/master_preferences
    state: absent

#/opt/google/chrome/master_preferences
- name: Nabigatzailea konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/chromium/master_preferences"
    dest: "/etc/chromium/master_preferences"
    mode: 0644
