#Google chrome instalatu eta politikak ezarri. Repositorioetan chromium dago baina...
#Ubuntun chromium paketea snap bidez instalatzen da eta ez zaigu gustatzen.
#Debianen meet-en funtzio batzuk desaktibatuta daude chromium instalatzerakoan.
---
#- name: Google-ren repoa gehitu.
#  deb822_repository:
#    name: google-chrome
#    types: deb
#    uris: https://dl.google.com/linux/chrome/deb/
#    components: stable main
#    architectures: amd64
#    signed_by: https://dl.google.com/linux/linux_signing_key.pub

- name: Google-ren repoaren sinadura gehitu.
  ansible.builtin.apt_key:
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Google-ren repoa gehitu.
  apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome

- name: Sistema eguneratu, repo berria irakurtzeko.
  apt:
    update_cache: yes

- name: Google Chrome instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - google-chrome-stable

#Script bat erabiltzen dugu irekitzerakoan aukerak gehituz.
- name: Abiarazteko aukerak gehitzen dituen script-a kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/chrome"
    dest: "/usr/local/bin/chrome"
    mode: 0755

- name: Chrome esteka sortu /usr/bin barruan.
  file:
    src: /usr/local/bin/chrome
    dest: /usr/bin/google-chrome-stable
    state: link

- name: Eguneratzailea kendu.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/cron.daily/google-chrome"
    - "/opt/google/chrome/cron"

- name: Politiken karpeta sortu.
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: 0755

- name: Politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/opt/chrome/policies/managed/policies.json"
    mode: 0644

#/opt/google/chrome/master_preferences orokorra
- name: Nabigatzailea konfiguratu orokorrean.
  copy:
    src: "{{ role_path }}/files/etc/chromium/master_preferences"
    dest: "/opt/google/chrome/initial_preferences"
    mode: 0644
