#Ataza honek mahaigaina instalatu eta konfiguratzen du
#xfce eta lightdm erabiltzen ditugu
---
  - include_tasks: 01-xorg_lightdm.yml

  - include_tasks: 02-locales.yml

  - include_tasks: 03-xfce.yml

  - include_tasks: 04-multimedia.yml

  - include_tasks: 05-compression.yml

  - include_tasks: 06-pdf.yml

  - include_tasks: 07-arbela.yml
