#Ataza honek repositorioak konfiguratzen ditu. "var" karpetatik Debian edo Ubunturenak aukeratzen ditu.
---
#- name: Google-ren repoa gehitu.
#  deb822_repository:
#    name: google-chrome
#    types: deb
#    uris: https://dl.google.com/linux/chrome/deb/
#    suites: "{{ ansible_distribution_release }}"
#    components: stable main
#    architectures: amd64
#    signed_by: https://dl.google.com/linux/linux_signing_key.pub

- name: updates repoa gehitu.
  apt_repository:
    repo: "{{ item  }} {{ repo }} {{ ansible_distribution_release }}-updates {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"

- name: backports repoa gehitu.
  apt_repository:
    repo: "{{ item  }} {{ repo }} {{ ansible_distribution_release }}-backports {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"

- name: Debian security repoa gehitu.
  apt_repository:
    repo: "{{ item }} http://security.debian.org/debian-security {{ ansible_distribution_release }}-security {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"
  when: ansible_distribution == 'Debian'

- name: Ubuntu security repoa gehitu.
  apt_repository:
    repo: "{{ item }} http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"
  when: ansible_distribution == 'Ubuntu'

- name: sources.list fitxategi originala kendu.
  file:
    path="/etc/apt/sources.list"
    state=absent

- name: standard repoa gehitu.
  apt_repository:
    repo: "{{ item  }} {{ repo }} {{ ansible_distribution_release }} {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"

- name: "apt-get update"
  apt:
    update_cache: yes
