#Ataza honek oinarrizko programa batzuk instalatzen ditu gure sisteman.
---
- name: Sistema eguneratu.
  apt:
    upgrade: dist

- name: Libreak ez diren firmware batzuk instalatu. Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux
    - firmware-linux-nonfree
  when: ansible_distribution == 'Debian'

- name: Programa extra batzuk instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - rsync
    - screen
    - nfs-common
    - watchdog
    - atool
    - bzip2
    - rar
    - p7zip-full
    - ipxe
    - sudo
    - ntfs-3g
    - cifs-utils
    - util-linux-locales
    - console-data

 #- name: Inxi eta bideo driverrak instalatu.
 # apt:
 #   name: "{{ packages }}"
 #   install_recommends: no
 # vars:
 #   packages:
 #   - inxi
 #   - mesa-utils
