#Ataza honek network-manager instalatzen du. Ubuntuko netplan konfigurazioan network-manager erabiltzeko esaten diogu.
---
- name: network-manager instalatu.
  apt:
    name: "network-manager"
    install_recommends: no

- name: Erabili NetworkManager sistema honen sareak kudeatzeko. Ubuntu.
  copy:
    src: "{{ role_path }}/files/etc/netplan/001-network-manager-all.yaml"
    dest: "/etc/netplan/01-network-manager-all.yaml"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'
