#Ataza honek repositorioak konfiguratu eta programa batzuk instalatzen ditu.
#Gainera gure konfigurazio batzuk jarri eta script batzuk kopiatzen ditu.
---
  - include_vars: "{{ ansible_distribution }}.yml"

  - include_tasks: 01-repositories.yml

  - include_tasks: 02-packages.yml

  - include_tasks: 03-customtweaks.yml

  - include_tasks: 04-networkmanager.yml

#  - include_tasks: 05-gitansible.yml
