#Rol honek aldi baterako fitxategiak ezabatuko ditu eta sistema squashfs fitxategi batetan konprimatuko du.
---
  - name: ezabatu hostname fitxategia, bezeroak automatikoki berria lortuko du
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/etc/hostname

  - name: ezabatu resolv.conf fitxategia, bezeroak automatikoki bat sortuko du
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/etc/resolv.conf

  - name: aldi baterako fitxategiak ezabatu.
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/apt/archives/*.deb

  - name: aldi baterako fitxategiak ezabatu.
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/apt/archives/partial/*

  - name: aldi baterako fitxategiak ezabatu.
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/debconf/*-old

  - name: aldi baterako fitxategiak ezabatu.
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/lib/apt/lists/*

  - name: vmlinuz kopiatu. Debian
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/vmlinuz"
      dest: "{{ inventory_hostname }}/vmlinuz"
      mode: 0644
    when: distro == 'debian'

  - name: initrd kopiatu. Debian
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/initrd.img"
      dest: "{{ inventory_hostname }}/initrd.img"
      mode: 0644
    when: distro == 'debian'

  - name: vmlinuz kopiatu. Ubuntu
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/boot/vmlinuz"
      dest: "{{ inventory_hostname }}/vmlinuz"
      mode: 0644
    when: distro == 'ubuntu'

  - name: initrd kopiatu. Ubuntu
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/boot/initrd.img"
      dest: "{{ inventory_hostname }}/initrd.img"
      mode: 0644
    when: distro == 'ubuntu'

  - name: filesystem.squashfs fitxategia sortu.
    command: chdir={{ inventory_hostname }}/live mksquashfs squashfs-root filesystem.squashfs

  - name: squashfs-root karpeta ezabatu.
    file:
      path="{{ inventory_hostname }}/live/squashfs-root"
      state=absent

  - name: md5 fitxategi zaharra kendu.
    file:
      path: "{{ inventory_hostname }}/live/filesystem.md5"
      state: absent

  - name: md5 checksum-a lortu.
    stat:
      path: "{{ inventory_hostname }}/live/filesystem.squashfs"
      checksum_algorithm: md5
      get_checksum: yes
    register: md5

  - name: md5 fitxategia sortu.
    lineinfile:
      path: "{{ inventory_hostname }}/live/filesystem.md5"
      line: "{{ md5.stat.checksum }} /run/live/medium/live/filesystem.squashfs"
      create: "true"
