#dnsmas eta nfs zerbitzaria prestatu
---
- name: Beharrezko programak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dnsmasq
    - nfs-kernel-server
    - python3-distutils-extra

- name: dnsmasq pxe konfiguratu, txantiloi bidez.
  template:
    src: "{{ role_path }}/templates/etc/dnsmasq.d/pxe.j2"
    dest: "/etc/dnsmasq.d/pxe"
    mode: 0644

#- name: Begiratu zerbitzari hau samba zerbitzaria den.
#  stat:
#    path: /etc/dnsmasq.d/samba
#  register: samba

- name: dnsmasq-en dns funtzioak desgaitu.
  template:
    src: "{{ role_path }}/templates/etc/dnsmasq.d/nodns.j2"
    dest: "/etc/dnsmasq.d/nodns"
    mode: 0644
#  when: samba.stat.exists == False

- name: tftp-root karpeta sortu.
  file:
    path: "{{ tftp_root }}"
    state: directory
    mode: 0755

- name: tftp-root karpeta nfs bidez partekatu.
  blockinfile:
    dest: "/etc/exports"
    block: |
     {{ tftp_root }}       *(ro,async,no_subtree_check)

- name: dnsmasq berrabiarazi.
  service:
    name: dnsmasq
    state: restarted

- name: nfs-kernel-server berrabiarazi.
  service:
    name: nfs-kernel-server
    state: restarted

#this module does not currently support using glob patterns
#this is why I restart each service at once
#- name: Restart services.
#  service:
#    name: "{{ services }}"
#    state: restarted
#  vars:
#    services:
#    - dnsmasq
#    - nfs-kernel-server
