#Zerbitzaria gure bezero live propioak sortzeko prestatu
---
- name: Beharrezko progamak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debootstrap
    - squashfs-tools
    - whois
    - zstd
#whois erabiltzaileen pasahitz enkriptatuak sortzeko erabiliko dugu
#zstd ubunturen azken bertsioetan derrigorrezkoa da, apt erabiltzeko

#Ubunturen bertsio berriek gutsy erabiltzen dute defektuz. Beraz, estekak eskuz sortu ditzakegu.
#http://changelogs.ubuntu.com/changelogs/pool/main/d/debootstrap/debootstrap_1.0.128+nmu2ubuntu4/changelog
- name: ubuntu lunar eta ubuntu noble-rentzat estekak sortu.
  file:
    src: "gutsy"
    dest: "/usr/share/debootstrap/scripts/{{ item }}"
    state: link
  with_items:
     - lunar
     - noble
