#zerbitzaritik windows instalatzeko aukera gehitu, bios eta uefi sistemetan. windows-en iso-a eskuz gehitu behar da.
---
- name: wimtools instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - wimtools
    - cabextract
    - genisoimage

- name: winpe karpeta sortu.
  file:
    path: "{{ tftp_root }}/windows"
    state: directory
    mode: 0755

- name: wimboot deskargatu eta erauzi.
  unarchive:
    src: http://git.ipxe.org/releases/wimboot/wimboot-latest.tar.gz
    dest: "{{ tftp_root }}/windows"
    remote_src: yes

- name: wimboot tft-root-era kopiatu.
  copy:
    src: "{{ tftp_root }}/windows/wimboot-2.6.0-signed/wimboot"
    dest: "{{ tftp_root }}/windows/wimboot"
    mode: 0644

- name: wimboot deskargatu dugun karpeta kendu.
  file:
    path: "{{ tftp_root }}/windows/wimboot-2.6.0-signed"
    state: absent

- name: memdisk tft-root-era kopiatu.
  copy:
    src: "/usr/lib/syslinux/memdisk"
    dest: "{{ tftp_root }}/windows/memdisk"
    mode: 0644
