#chroot-etik atera aurretik eman beharreko pausoak
---
- name: APT-ren katxea hustu.
  apt:
    autoclean: yes

- name: Ezabatu automatikoki instalatu eta jada beharrezkoak ez diren programak.
  apt:
    autoremove: yes

- name: proc desmuntatu
  mount:
    path: /proc
    state: absent

- name: sys desmuntatu
  mount:
    path: /sys
    state: absent

- name: devpts desmuntatu
  mount:
    path: /dev/pts
    state: absent
