#hainbat rol exekutatzen dituen playbook-a. 
#-debootstrap-ek sistema minimo bat sortuko du (oso mugatua).
#-installer-ek debianen instalatzailearen pausoak emango ditu (hizkuntza konfiguratu, erabiltzaileak sortu...).
#-minimal-ek guk aukeratutako programa eta konfigurazio batzuk gehituko ditu.
#-desktop-ek ingurune grafikoa instalatuko du (hau "desktops" taldearen barruan daudenek erabiliko dute bakarrik).
#-squash-ek baterako fitxategiak ezabatu eta filesystem.squash fitxategia sortuko du.
---
- hosts: all
  connection: local
  roles:
    - debootstrap

- hosts: all
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include_tasks: prepare.yml
    - include_role:
        name: installer
    - include_role:
        name: minimal
    - include_role:
        name: sambaclient
    - include_tasks: exit.yml

- hosts: desktops
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include_tasks: prepare.yml
    - include_role:
        name: desktop
    - include_tasks: exit.yml

- hosts: all
  connection: local
  roles:
    - squash
