#chroot-era sartu aurretik egingo diren pausoak. Bestela programa batzuen instalazioan akatsak egon daitezke.
---
- name: Mount proc
  mount:
    src: none
    path: /proc
    fstype: proc
    state: mounted

- name: Mount sys
  mount:
    src: none
    path: /sys
    fstype: sysfs
    state: mounted

- name: Mount devpts
  mount:
    src: none
    path: /dev/pts
    fstype: devpts
    state: mounted

#debootstrap-ek DNS-ak konfiguratzen ditu. 
#Baina aurretik sortutako filesystem.squash bat aldatu nahi badugu, konfigurazio hori ez da existitzen (squash rolak kentzen duelako)
- name: Begiratu resolv.conf existitzen den.
  stat:
    path: "/etc/resolv.conf"
  register: resolvconf

- name: Ez denez resolv.conf existitzen, bat sortu.
  blockinfile:
    dest: "/etc/resolv.conf"
    create: "true"
    block: |
     nameserver 8.8.8.8
  when: resolvconf.stat.exists == False

#i386 arkitekturako bezero bat sortu badugu, chroot barruan ansiblek ez du ondo detektatzen (zerbitzaria amd64 delako). Eskuz jartzen dugu.
- name: i386 bezeroa bada, jarri ondo arkitektura, ez erabili zerbitzariarena.
  set_fact:
    ansible_architecture: i386
  when: arch == 'i386'

- name: "'apt-get update' exekutatu"
  apt:
    update_cache: yes
