#Ataza honetan sistema euskeraz jarriko dugu
---
- name: Instalatu euskera eta gaztelaniako lokalak. Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - language-pack-es
    - language-pack-eu
  when: ansible_distribution == 'Ubuntu'

- name: Aktibatu gaztelaniako lokala.
  locale_gen:
    name: es_ES.UTF-8
    state: present
  register: spanish

- name: Aktibatu euskerako lokala.
  locale_gen:
    name: eu_ES.UTF-8
    state: present
  register: basque

- name: Aldaketak egon badira "dpkg-reconfigure" exekutatu konfigurazioa eguneratzeko.
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive locales
  when: (spanish is changed) or (basque is changed)

- name: Sistemaren defektuzko hizkuntza euskera jarri. Euskerazko itzulpena ez duten programetan gaztelera erabili.
  command: /usr/sbin/update-locale LANG=eu_ES.UTF-8 LANGUAGE=eu:es
