#Ataza honetan teklatu espainiarra konfiguratzen dugu. Karaktereentzako UTF-8 sistema jartzen dugu.
---
- name: Keyboard-configuration eta console-setup instalatu. Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - keyboard-configuration
    - console-setup
    - console-data
  when: ansible_distribution == 'Debian'

- name: Aldatu /etc/default/keyboard teklatua espainiarra dela esateko.
  lineinfile:
    dest: /etc/default/keyboard
    regexp: 'XKBLAYOUT="us"'
    line: 'XKBLAYOUT="es"'
    backrefs: yes
  register: keyboard

- name: Aldatu /etc/default/console-setup UTF-8 erabiltzeko.
  lineinfile:
    dest: /etc/default/console-setup
    regexp: 'CHARMAP="ISO-8859-15"'
    line: 'CHARMAP="UTF-8"'
    backrefs: yes
  register: charset

- name: Aldaketak egon badira "dpkg-reconfigure" exekutatu konfigurazioa eguneratzeko.
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive keyboard-configuration
  when: keyboard is changed

- name: Aldaketak egon badira "dpkg-reconfigure" exekutatu konfigurazioa eguneratzeko.
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive console-setup
  when: charset is changed
