#DNS-ak ez dira ondo konfiguratzen ubuntu live sistemetan. Debootstrap instalazioa oso sinplea denez pakete eta konfigurazioak falta dira.
#Ataza honek hori konpontzen du.
---
#systemd-networkd zerbitzuari sarea dhcp bidez konfiguratzeko esango diogu.
#hasierako abiarazleak (syslinux, grub, ipxe...) ip-a dchp bidez lortzeko esaten du ere.
- name: Ubuntu sarea konfiguratu systemd erabiliz.
  copy:
    src: "/lib/systemd/network/89-ethernet.network.example"
    dest: "/etc/systemd/network/89-ethernet.network"
    mode: 0644
    remote_src: true

#Sistema disko gogorrean instalatuko bagenu "dhclient" eskuz exekutatu behar dugu. Horregatik instalatzen dugu.
#systemd-networkd zerbitzua aktibatuz ere egin liteke
- name: Install isc-dhcp-client.
  apt:
    name: "isc-dhcp-client"
    install_recommends: no
