#Ataza honek bi gauza egiten ditu
#-root erabiltzailearen pasahitza jartzen du ("root"). Debianen bakarrik.
#-"user" izeneko erabiltzailea sortzen du "user" pasahitzarekin. Ubuntun eta Debianen.
#pasahitzak sortzeko 'mkpasswd --method=sha-512' komandoa erabili. Whois programa instalatuta egon behar da.
---
    - name: root pasahitza ezarri. Debian.
      user:
         name: root
         password: $6$XtIYIO4tP9tuuCSK$Gfn6H0peyqVJ.KsOaXBQNJpsoiOMgcB0afL/5s/5zN33CmIuDdFaPEvmkZze/I/6C53GLbQF3U29uu39W5T/H1
      when: ansible_distribution == 'Debian'

    - name: Erabiltzaile berria sortu. Debian.
      user:
         name: user
         password: $6$yfBEPbX/HQai$gc0qCZdrLUiSlw21LbRrfBsDtZ9cpjBisV.b.HCiaN/17x0NEnYNvF8JGsEYaOVHiiYUOAgnAc9wMQkrQaeOu/
         shell: /bin/bash
         createhome: no
         groups: cdrom,floppy,audio,dip,video,plugdev,netdev,sudo,render
      register: user
      when: ansible_distribution == 'Debian'

    - name: Erabiltzaile berria sortu. Ubuntu.
      user:
         name: user
         password: $6$yfBEPbX/HQai$gc0qCZdrLUiSlw21LbRrfBsDtZ9cpjBisV.b.HCiaN/17x0NEnYNvF8JGsEYaOVHiiYUOAgnAc9wMQkrQaeOu/
         shell: /bin/bash
         createhome: no
         groups: adm,cdrom,dip,plugdev,sudo,render
      register: user
      when: ansible_distribution == 'Ubuntu'

    - name: Erabiltzailearen karpeta nagusia lehen aldiz sartzerakoan sortu.
      replace:
        dest: /usr/share/pam-configs/mkhomedir
        regexp: 'Default: no'
        replace: 'Default: yes'
      register: pam

    - name: pam-auth-update
      command: pam-auth-update --package --enable mkhomedir
      when: (user is changed) or (pam is changed)
