#Ataza honek kernela instalatzen du.
---
- name: 32 biteko kernela instalatu. Debian.
  apt: name=linux-image-686-pae
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'i386'

- name: 64 biteko kernela instalatu. Debian.
  apt: name=linux-image-amd64
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'x86_64'

- name: 64 biteko kernela instalatu. Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - linux-image-generic
  when: ansible_distribution == 'Ubuntu'
