#Ataza honek grub instalatzen du eta ubunturen bug bat konpontzen du
---
- name: Grub instalatu.
  apt:
    name: grub-pc

- name: 64 biteko sistemetan EFI bertsioa instalatu ere.
  apt:
    name: grub-efi-amd64-signed
  when: ansible_architecture == 'x86_64'

- name: Ubunturen 30 segunduen bug-a konpondu.
  lineinfile:
    path: /etc/default/grub
    insertafter: '^(.*)GRUB_TIMEOUT=(.*)$'
    line: 'GRUB_RECORDFAIL_TIMEOUT=2'
  when: ansible_distribution == 'Ubuntu'
